# Generated by Django 4.1.2 on 2022-11-07 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_city', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_file', models.FileField(default=None, upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_province', models.CharField(max_length=40)),
                ('the_city', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.city')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_as',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('phone_number', models.IntegerField(blank=True, default=None, null=True)),
                ('CreatDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('password', models.CharField(default=None, max_length=25, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.city')),
                ('profile_image', models.ManyToManyField(blank=True, default=None, related_name='image_profile', to='main.file')),
                ('province', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.province')),
                ('username', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.user')),
            ],
        ),
    ]
